input-output-hk/cardano-sl-explorer

README.md
frontend/bower.json
frontend/scripts/build.sh
frontend/src/Explorer/Types/Actions.purs
frontend/src/Explorer/Update.purs
frontend/src/Explorer/Util/QRCode.js
frontend/src/Explorer/Util/QRCode.purs
frontend/src/Explorer/View/Address.purs
scripts/build.sh

Added QR generation. Added a simple script in root, added in _frontend/scripts/build.sh_:
> nix-shell --run "rm -rf .psci_modules/ .pulp-cache/ node_modules/ bower_components/ output/"

[CSE-52] QR code generation library

---

frontend/src/Explorer/Util/Factory.purs

[CSE-42] Fix sumCoinOfInputsOutputs

---

docs/cardano-explorer-web-api.md
frontend/bower.json
frontend/package.json
frontend/src/Explorer/I18n/DE.purs
frontend/src/Explorer/I18n/EN.purs
frontend/src/Explorer/I18n/Types.purs
frontend/src/Explorer/Util/Time.Test.purs
frontend/src/Explorer/Util/Time.purs
frontend/src/Explorer/View/Address.purs
frontend/src/Explorer/View/Block.purs
frontend/src/Explorer/View/Common.purs
frontend/src/Explorer/View/Dashboard/Transactions.purs
frontend/src/Explorer/View/Transaction.purs

[CSE-58] Prettify time format

---

docs/cardano-explorer-table-web-api.md
docs/cardano-explorer-web-api.md
src/Pos/Explorer/Web/Doc.hs
src/Pos/Explorer/Web/Server.hs
src/documentation/Main.hs

Also fixed some smaller things from [CSM-132].

[CSM-167] Create automatic REST api table documentation

---

src/Pos/Explorer/Web/ClientTypes.hs

Transactions:
```
curl http://localhost:8100/api/txs/summary/1
{"Left":"Invalid transaction id!"}
curl http://localhost:8100/api/txs/last
{"Right":[{"cteId":"2ca9c11371edf243150acdbe1e9bc6f7c2b9e76508ff126abe672f05c0657aef","cteTimeIssued":1.490962457991294e9,"cteAmount":{"getCoin":33333}}]}
curl http://localhost:8100/api/txs/summary/2ca9c11371edf243150acdbe1e9bc6f7c2b9e76508ff126abe672f05c0657aef
{"Right":{"ctsId":"2ca9c11371edf243150acdbe1e9bc6f7c2b9e76508ff126abe672f05c0657aef","ctsTxTimeIssued":1.490962457991294e9,"ctsBlockTimeIssued":null,"ctsBlockHeight":29,"ctsRelayedBy":null,"ctsTotalInput":{"getCoin":33333},"ctsTotalOutput":{"getCoin":33333},"ctsFees":{"getCoin":0},"ctsInputs":[["1fi9sA3pRt8bKVibdun57iyWG9VsWZscgQigSik6RHoF5Mv",{"getCoin":33333}]],"ctsOutputs":[["1f3RwhKazQsNhWoeY …
```

[CSM-160] Removing checks

---

src/Pos/Explorer/Aeson/ClientTypes.hs
src/Pos/Explorer/Web/Api.hs
src/Pos/Explorer/Web/ClientTypes.hs
src/Pos/Explorer/Web/Doc.hs
src/Pos/Explorer/Web/Server.hs

Link to issue - https://issues.serokell.io/issue/CSM-186
Removing what https://issues.serokell.io/issue/CSM-132 added.

[CSM-186] Remove search for address/transaction/block.

---

frontend/src/Explorer/I18n/DE.purs
frontend/src/Explorer/I18n/EN.purs
frontend/src/Explorer/I18n/Types.purs
frontend/src/Explorer/View/Dashboard/Network.purs

because we won't have any kind of "network difficulty".

Remove "network difficulty"

---

src/Pos/Explorer/Web/Server.hs

Raise **"No epoch/slots found."**  if epoch/slot search returns `[]` so it's consistent to the rest of the search functions.

[CSM-169] Raise exception when list empty.

---

frontend/src/Explorer/View/Common.purs
frontend/src/Explorer/View/Dashboard/api.css
frontend/src/Explorer/View/Dashboard/dashboard.css
frontend/src/Explorer/View/Dashboard/transactions.css
frontend/src/Explorer/View/Types.purs
frontend/src/Explorer/View/common.css
frontend/src/Explorer/View/footer.css
frontend/src/Explorer/View/header.css
frontend/src/Explorer/View/transaction.css
frontend/src/global.css

- Transaction detail page
- misc. fixes

[CSE-35] mooore responsive content

---

stack.yaml

Here is the change. I checked - I though I pushed the change, but since you added protection to the branch I got `remote: error: Required status check "continuous-integration/travis-ci" is expected. At least one approved review is required`.

[CSM-215] Bump time-warp commit.

---

start-dev.sh

Tested with both:
```
./start-dev.sh
./start-dev.sh /home/ksaric/projects/haskell/cardano-sl
```

[CSE-76] Fix start-dev script

---

frontend/src/Explorer/View/Dashboard/hero.css
frontend/src/Explorer/View/Header.purs

- on desktop only
- Fix offset of search UI in hero

[CSE-74] Fix: Add missing search UI into header

---

frontend/bower.json
frontend/src/Explorer/State.purs
frontend/src/Explorer/Types/Actions.purs
frontend/src/Explorer/Types/State.purs
frontend/src/Explorer/Update.purs
frontend/src/Explorer/View/Blocks.purs
frontend/src/Main.purs
src/explorer/Main.hs

@jmitchell note that I have added new dependency:
```
$ bower install --save purescript-now#v2.0.0
bower purescript-now#v2.0.0 not-cached https://github.com/garyb/purescript-now.git#v2.0.0
bower purescript-now#v2.0.0    resolve https://github.com/garyb/purescript-now.git#v2.0.0
bower purescript-now#v2.0.0   download https://github.com/garyb/purescript-now/archive/v2.0.0.tar.gz
bower purescript-now#v2.0.0    extract archive.tar.gz
bower purescript-now#v2.0.0   resolved https://github.com/garyb/purescript-now.git#2.0.0
bower purescript-now#v2.0.0    install purescript-now#2.0.0
purescript-now#2.0.0 bower_components/purescript-now
├── purescript-datetime#2.2.0
└── purescript-eff#2.0.0
```

[WIP] [CSE-87] Fix time duration

---

frontend/src/Explorer/I18n/JP.purs
frontend/src/Explorer/I18n/Lang.purs
frontend/src/Explorer/State.purs
frontend/src/Explorer/View/Block.purs
frontend/src/Explorer/View/Blocks.purs
frontend/src/Explorer/View/Common.purs
frontend/src/Explorer/View/Dashboard/Dashboard.purs
frontend/src/Explorer/View/Dashboard/Transactions.purs
frontend/src/Explorer/View/Transaction.purs
frontend/src/Explorer/View/search.css

- Support lang JP
- fix warnings of imports
- fix React warning to `defaultValue` (instead of `selected`)

[CSE-96] Support JP

---

frontend/src/Explorer/I18n/DE.purs
frontend/src/Explorer/I18n/EN.purs
frontend/src/Explorer/I18n/JP.purs
frontend/src/Explorer/I18n/Types.purs
frontend/src/Explorer/View/Transaction.purs

`transaction fee` instead of `transaction feed`

[CSE-79] fix typo

---

frontend/src/Explorer/I18n/DE.purs
frontend/src/Explorer/I18n/EN.purs
frontend/src/Explorer/I18n/JP.purs

Issue https://issues.serokell.io/issue/CSE-101

[CSE-101] Change heading sentence

---

frontend/src/Main.purs

Workarounds this problem https://issues.serokell.io/issue/CSE-102

[CSE-102] Slow down requests

---

frontend/src/Explorer/View/Common.purs

https://issues.serokell.io/issue/CSE-105

[CSE-105] Fix pagination render

---

src/Pos/Explorer/Web/Server.hs

Continuation of https://github.com/input-output-hk/cardano-sl-explorer/pull/88 with changed base branch.

[CSE-110] Return number of txs with address summary

---

frontend/src/Explorer/I18n/DE.purs
frontend/src/Explorer/I18n/EN.purs
frontend/src/Explorer/I18n/JP.purs
frontend/src/Explorer/Types/Actions.purs
frontend/src/Explorer/Update.purs
frontend/src/Explorer/View/Blocks.purs
frontend/src/Explorer/View/Common.purs
frontend/src/Main.purs

Reverts input-output-hk/cardano-sl-explorer#80
Was merged accidentally

Revert "[WIP] Fix/cse 98 disable socketio"

---

frontend/package.json
frontend/src/Data/Time/NominalDiffTime.Test.purs
frontend/src/Data/Time/NominalDiffTime.purs
frontend/src/Explorer/Api/Http.purs
frontend/src/Explorer/State.purs
frontend/src/Explorer/Types/Actions.purs
frontend/src/Explorer/Types/State.purs
frontend/src/Explorer/Update.Test.purs
frontend/src/Explorer/Update.purs
frontend/src/Explorer/Util/Data.Test.purs
frontend/src/Explorer/Util/Data.purs
frontend/src/Explorer/Util/Factory.purs
frontend/src/Explorer/Util/Sort.Test.purs
frontend/src/Explorer/Util/Sort.purs
frontend/src/Explorer/View/Blocks.purs
frontend/src/Explorer/View/CSS.purs
frontend/src/Explorer/View/Dashboard/Blocks.purs
frontend/src/Explorer/View/Dashboard/Transactions.purs
frontend/src/Explorer/View/blocks.css
frontend/src/Main.Test.purs
frontend/src/Test/MockFactory.purs
frontend/test/rename-placeholders.js
frontend/test/setup.js
frontend/yarn.lock

[CSE-92] Fix blocks pagination

---

.gitignore
log-config.yaml

https://issues.serokell.io/issue/CSE-128
Switching to `Error` severity and adding a separate file for **socket.io** logging.

CSE-128 Change logging

---

frontend/src/Explorer/Api/Types.purs
frontend/src/Explorer/State.purs
frontend/src/Explorer/Update.Test.purs
frontend/src/Explorer/Update.purs
frontend/src/Main.purs

https://issues.serokell.io/CSE-122

CSE-122 socket.io stops working in some instances fixed

---

frontend/src/Explorer/View/common.css

It is just a tiny fix for Firefox.

[CSE-124] Fix cross-browser issues

---

frontend/src/Explorer/Api/Types.purs
frontend/src/Explorer/State.purs
frontend/src/Explorer/Types/Actions.purs
frontend/src/Explorer/Types/State.purs
frontend/src/Explorer/Update.Test.purs
frontend/src/Explorer/Update.purs

[CSE-138] Improve subscription / un-subscription 

---

frontend/package.json
frontend/src/Explorer/View/Footer.purs
frontend/src/Explorer/View/footer.css

Version number + commit hash in footer. Commit hash is clickable and linked to commit page of GitHub.

[CSE-123] Add version no. + commit hash to footer

---

src/Pos/Explorer/Web/Server.hs

https://issues.serokell.io/issue/CSE-136
**Also, changed default `limit` to 10.**
This is a much more verbose and simple version that fixes the bug(s).

CSE-136 Results of endpoints  and  aren't match as expected

---

frontend/src/Explorer/I18n/DE.purs
frontend/src/Explorer/I18n/EN.purs
frontend/src/Explorer/I18n/JP.purs
frontend/src/Explorer/I18n/Types.purs
frontend/src/Explorer/State.purs
frontend/src/Explorer/Types/State.purs
frontend/src/Explorer/Update.purs
frontend/src/Explorer/View/Address.purs
frontend/src/Explorer/View/Block.purs
frontend/src/Explorer/View/Blocks.purs
frontend/src/Explorer/View/Common.purs
frontend/src/Explorer/View/Dashboard/Shared.purs
frontend/src/Explorer/View/block.css
frontend/src/Explorer/View/common.css

- `currentBlockSummary` + `currentBlockTxs` are of type `RemoteData` now
- plus few tiny css fixes (just paddings + margins)

[CSE-137] UI feedback if a slot has not be found

---

frontend/README.md
scripts/build.sh

https://issues.serokell.io/issue/CSE-90
Fixed README and `build.sh`.

CSE-90 Update README.

---

frontend/src/index.tpl.html

- conditional comments based on https://www.quirksmode.org/css/condcom.html
- Link to https://browsehappy.com
Manual tested with IE 9, IE 10 (all Windows) and latest FF / Chrome (on macOS).

[CSE-150] No support of IE < 10

---

frontend/src/Explorer/Api/Socket.purs
frontend/src/Explorer/Api/Types.purs
frontend/src/Explorer/Types/Actions.purs
frontend/src/Explorer/Update.Test.purs
frontend/src/Explorer/Update.purs
frontend/src/Main.purs
frontend/src/Test/MockFactory.purs
src/Pos/Explorer/Socket/App.hs
src/Pos/Explorer/Socket/Methods.hs
src/Pos/Explorer/Socket/Util.hs
src/Pos/Explorer/Web/ClientTypes.hs
src/Pos/Explorer/Web/Server.hs
stack.yaml

to update transactions of address detail page.
_Note:_ This is a PR of changes of back- (`CSE-153`) and frontend (`CSE-152`) (all teamwork by @Martoon-00 / @sectore)

[CSE-152] Subscribe `AddrUpdated` events

---

log-config.yaml
src/Pos/Explorer/Socket/Methods.hs

In CSE-146 I broke displaying of logs, those which are not mentioned in `log-config.yaml`.

[CSE-146] Fix logging

---

src/explorer/ExplorerOptions.hs
src/explorer/Params.hs
stack.yaml

@ksaric this one should catch up on latest `cardano-sl-0.5-rc` branch

sync with cardano-sl-0.5

---

src/Pos/Explorer/Web/Server.hs
stack.yaml

https://issues.serokell.io/issue/CSE-156
Switched the implementation to use the last available page - https://issues.serokell.io/issue/CSE-156#comment=96-5068
Also, bumped `purescript-bridge` - https://issues.serokell.io/issue/CSM-322#comment=96-5069

Block pages hangs cpu

---

src/explorer/Main.hs
stack.yaml

Bumped to newest `cardano-sl`.

Bumped explorer to newset cardano-sl.

---

frontend/src/Explorer/State.purs
frontend/src/Explorer/Types/State.purs
frontend/src/Explorer/Update.purs
frontend/src/Explorer/View/Header.purs

Headline of mobile header is not updated if the language was changed. This PR does fix this issue.

[CSE-171] Fix mobile headline translation

---

frontend/src/Explorer/View/Dashboard/dashboard.css

which is visible on small mobile devices only. That's the only (tiny) bug I have found testing Android devices today.

[CSE-149] Fix breaking headline

---

frontend/src/Explorer/State.purs
frontend/src/Explorer/Types/State.purs
frontend/src/Explorer/Update.Test.purs
frontend/src/Explorer/Update.purs

which was set to previous value while loading data of blocks.

[CSE-173] Fix value of page number

---

scripts/run.sh
src/Pos/Explorer/Web/Api.hs
src/Pos/Explorer/Web/Server.hs
src/Pos/Explorer/Web/TestServer.hs
src/Pos/Explorer/Web/Transform.hs
src/documentation/Main.hs
src/explorer/Main.hs
stack.yaml
start-dev.sh

https://issues.serokell.io/issue/CSE-162
Finally. It seems to work correctly, there is a small issue that I still have to check on the first page, otherwise seems to work great.
Most of the work done on the `cardano-sl` backend - https://github.com/input-output-hk/cardano-sl/blob/cardano-sl-0.5-rc/src/Pos/Explorer/BListener.hs
@gromakovsky I used `runRealBasedMode` which seems to fix those issues with the tagged identity transformer redirect.

CSE-162 explorer slow blocks

---

README.md
cardano-sl-explorer.cabal
scripts/build/cardano-sl.sh
scripts/launch/staging.sh
src/explorer/Main.hs

Issue here https://issues.serokell.io/issue/CSE-175

[CSE-175] Add testnet sripts. Remove depricated CPP pragmas

---

scripts/launch/staging.sh
src/Pos/Explorer/Web/Server.hs

https://issues.serokell.io/issue/CSE-169

CSE-169 Explorer slow epochs.

---

frontend/src/Explorer/View/Blocks.purs
frontend/src/Explorer/View/blocks.css
frontend/webpack.config.babel.js

@sectore I will need your help. This does hide it but it is padded to the left.

[CSE-159] Hide Since column

---

src/Pos/Explorer/Web/Transform.hs
stack.yaml

Bumped to commit `98b9ace02565d7270e4df48110601eacdb351546`.

Explorer bumped to commit.

---

CHANGELOG.md
frontend/src/Explorer/View/Footer.purs
scripts/build/clean.sh
src/Pos/Explorer/Web/Transform.hs
stack.yaml

https://issues.serokell.io/issue/CSE-178
Added fix for CSE-178 and other small fixes.

CSE-178 reverse db block order

---

frontend/src/Explorer/View/Block.purs
src/Pos/Explorer/Aeson/ClientTypes.hs
src/Pos/Explorer/Socket/App.hs
src/Pos/Explorer/Socket/Holder.hs
src/Pos/Explorer/Socket/Methods.hs
src/Pos/Explorer/Web/ClientTypes.hs
src/Pos/Explorer/Web/Server.hs
src/Pos/Explorer/Web/TestServer.hs
src/Pos/Explorer/Web/Transform.hs
src/explorer/ExplorerOptions.hs
src/explorer/Main.hs
src/explorer/Params.hs
stack.yaml

* Support tx fees
* Bump up to last `cardano-sl`:
** Remove `NotificationMode`, use `ReaderT` instead (because of we can't have several `MonadReader` in our monad stack now...)
** Simplify `Transformer.hs`
** Rewrite `Main.hs` and `ExplorerOptions.hs` with according to `cardano-sl/Main.hs`
FYI: I didn't test it, because it's required to compile purescript

[CSE-99] Support tx fees. Bump up cardano-sl.

---

frontend/src/Explorer/View/Transaction.purs
src/Pos/Explorer/Web/ClientTypes.hs
src/Pos/Explorer/Web/Server.hs
src/Pos/Explorer/Web/TestServer.hs

https://issues.serokell.io/issue/CSE-163
Fixed the problem with displaying mempool transactions.

CSE-163 functions not returning mempool tx

---

frontend/src/Explorer/Api/Http.purs
frontend/src/Explorer/I18n/DE.purs
frontend/src/Explorer/I18n/EN.purs
frontend/src/Explorer/I18n/JP.purs
frontend/src/Explorer/I18n/Types.purs
frontend/src/Explorer/State.purs
frontend/src/Explorer/Types/Actions.purs
frontend/src/Explorer/Types/State.purs
frontend/src/Explorer/Update.purs
frontend/src/Explorer/View/GenesisBlock.purs
frontend/src/Explorer/View/genesis.css
frontend/src/Test/MockFactory.purs
src/Pos/Explorer/Web/Api.hs
src/Pos/Explorer/Web/ClientTypes.hs
src/Pos/Explorer/Web/Server.hs
src/Pos/Explorer/Web/TestServer.hs

Backend part done, frontend part pending.

[CSE-193] Extend genesis page

---

scripts/build/cardano-sl.sh
scripts/launch/qa.sh
scripts/launch/staging.sh
start-dev.sh

Adds qa script. You can launch master on qa cluster:
```
scripts/build/cardano-sl.sh --qa
scripts/launch/qa.sh
```
Fixes dev launch script (missing script in cardano-sl repo). Merge after https://github.com/input-output-hk/cardano-sl/pull/1224

Add qa launch script (for master). Fix dev launch script

---

README.md
frontend/README.md
src/Pos/Explorer/Socket/App.hs

---
Youtrack issue URL
https://issues.serokell.io/issue/CSE-176
---
Short description 
* Simplify `CORS` handling
* Update `README`
* Keep `README` of front-end up-to-day (which was not really a task of `CSE-176`)
---
How did I test this new functionality/bug fix?
1. Branch `fix/CSE-176-simplify-cors`
2. Build in `DEV` by running ./start-dev.sh
3. Start front-end and check if blocks are updated
---

[CSE-176] Simplify cors

---

frontend/src/Explorer/Api/Http.purs
frontend/src/Explorer/Api/Socket.purs
frontend/src/Explorer/Api/Types.purs
frontend/src/Explorer/I18n/DE.purs
frontend/src/Explorer/I18n/EN.purs
frontend/src/Explorer/I18n/JP.purs
frontend/src/Explorer/I18n/Types.purs
frontend/src/Explorer/Routes.purs
frontend/src/Explorer/State.purs
frontend/src/Explorer/Types/Actions.purs
frontend/src/Explorer/Types/State.purs
frontend/src/Explorer/Update.Test.purs
frontend/src/Explorer/Update.purs
frontend/src/Explorer/View/Address.purs
frontend/src/Explorer/View/Block.purs
frontend/src/Explorer/View/Blocks.purs
frontend/src/Explorer/View/GenesisBlock.purs
frontend/src/Explorer/View/genesis.css
frontend/src/Main.purs
frontend/src/Test/MockFactory.purs
src/Pos/Explorer/Socket/App.hs
src/Pos/Explorer/Socket/Holder.hs
src/Pos/Explorer/Socket/Methods.hs
src/Pos/Explorer/Web/Api.hs
src/Pos/Explorer/Web/ClientTypes.hs
src/Pos/Explorer/Web/Server.hs
src/Pos/Explorer/Web/TestServer.hs

---
Youtrack issue URL - https://issues.serokell.io/issue/CSE-201
---
Short description - Merge `cardano-sl-0.5` into `master` so we can integrate all the changes to the migrated repository on `cardano-sl`.
---
How did I test this new functionality/bug fix?
I will test this once it get's merged to the `cardano-sl` repository.
---

CSE201 merge 0.5 into master
